name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - main
    tags:
      - v\d+\.\d+\.\d+

env:
  PROJECT_ID: devopsstorybooks

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV
        run: |-
          if [ ${GITHUB_REF##*/} = "main" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
          else 
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCE_SA_KEY }}  # Use this if you're using a service account key
          # OR for Workload Identity Federation, uncomment and configure the following lines:
          # workload_identity_provider: 'projects/123/locations/global/workloadIdentityPools/pool/providers'
          # service_account: '[email protected]'

      # Setup gcloud CLI with the latest version
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          version: '>= 363.0.0'  # Specify a compatible version

      # Configure Docker to use gcloud as credential helper
      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          make build

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          make push

      # Deploy the application
      - name: Deploy
        run: |-
          make deploy